In [259]:
import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from wordcloud import WordCloud
from sklearn.metrics import r2_score

In [260]:
df_award = pd.read_csv('nba/Player Award Shares.csv')
df_award = df_award.rename(columns={'player' : 'player_name'})

In [261]:
df_award

,season,award,player_name,age,tm,first,pts_won,pts_max,share,winner,seas_id,player_id
0,2022,dpoy,Marcus Smart,27,BOS,37.0,257.0,500.0,0.514,True,30183,4275
1,2022,dpoy,Mikal Bridges,25,PHO,22.0,202.0,500.0,0.404,False,30205,4658
2,2022,dpoy,Rudy Gobert,29,UTA,12.0,136.0,500.0,0.272,False,30313,4199
3,2022,dpoy,Bam Adebayo,24,MIA,13.0,128.0,500.0,0.256,False,29689,4472
4,2022,dpoy,Jaren Jackson Jr.,22,MEM,10.0,99.0,500.0,0.198,False,29991,4632
...,...,...,...,...,...,...,...,...,...,...,...,...
3219,1956,nba mvp,Mel Hutchins,27,FTW,9.0,9.0,80.0,0.113,False,1732,466
3220,1956,nba mvp,Dolph Schayes,27,SYR,2.0,2.0,80.0,0.025,False,1687,328
3221,1956,nba mvp,Bill Sharman,29,BOS,2.0,2.0,80.0,0.025,False,1652,419
3222,1956,nba mvp,Tom Gola,23,PHW,1.0,1.0,80.0,0.013,False,1748,607
3223,1956,nba mvp,Maurice Stokes,22,ROC,1.0,1.0,80.0,0.013,False,1729,602

In [262]:
df_career = pd.read_csv('nba/Player Career Info.csv')
df_career = df_career.rename(columns={'player' : 'player_name'})
df_career

,player_id,player_name,birth_year,hof,num_seasons,first_seas,last_seas
0,1,Al Brightman,NaN,False,1,1947,1947
1,2,Al Lujack,NaN,False,1,1947,1947
2,3,Al Negratti,NaN,False,1,1947,1947
3,4,Angelo Musi,NaN,False,3,1947,1949
4,5,Ariel Maughan,1923.0,False,5,1947,1951
...,...,...,...,...,...,...,...
5019,5020,Xavier Moon,NaN,False,1,2022,2022
5020,5021,Xavier Sneed,NaN,False,1,2022,2022
5021,5022,Yves Pons,NaN,False,1,2022,2022
5022,5023,Zavier Simpson,NaN,False,1,2022,2022
5023,5024,Ziaire Williams,NaN,False,1,2022,2022

In [263]:
df_playoff = pd.read_csv('nba/Team Stats Per 100 Poss.csv')
df_playoff = df_playoff.rename(columns={'abbreviation' : 'team_abbreviation'})
df_playoff

,season,lg,team,team_abbreviation,playoffs,g,mp,fg_per_100_poss,fga_per_100_poss,fg_percent,...,ft_percent,orb_per_100_poss,drb_per_100_poss,trb_per_100_poss,ast_per_100_poss,stl_per_100_poss,blk_per_100_poss,tov_per_100_poss,pf_per_100_poss,pts_per_100_poss
0,2022,NBA,Atlanta Hawks,ATL,True,82,19705,42.4,90.3,0.470,...,0.812,10.3,34.7,45.0,25.2,7.3,4.3,12.1,19.1,116.5
1,2022,NBA,Boston Celtics,BOS,True,82,19905,41.7,89.5,0.466,...,0.816,10.8,36.4,47.2,25.4,7.4,6.0,14.0,19.0,114.4
2,2022,NBA,Brooklyn Nets,BRK,True,82,19755,42.2,89.0,0.475,...,0.805,10.4,34.3,44.7,25.4,7.1,5.5,14.1,20.5,113.6
3,2022,NBA,Chicago Bulls,CHI,True,82,19730,42.3,88.2,0.480,...,0.813,8.8,34.2,42.9,24.2,7.2,4.2,13.0,19.1,113.2
4,2022,NBA,Charlotte Hornets,CHO,False,82,19880,42.3,90.5,0.468,...,0.740,10.7,33.4,44.1,27.8,8.5,4.9,13.1,19.7,114.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337,1974,ABA,San Antonio Spurs,SAA,True,84,20360,41.5,91.2,0.455,...,0.778,15.3,32.8,48.2,22.4,7.4,2.8,16.5,27.3,101.7
1338,1974,ABA,San Diego Conquistadors,SDA,True,84,20285,42.3,95.6,0.443,...,0.753,15.5,29.6,45.2,21.5,7.5,5.6,14.3,17.8,102.9
1339,1974,NBA,Seattle SuperSonics,SEA,False,82,19755,39.5,88.8,0.445,...,0.767,14.6,29.8,44.4,23.2,7.6,3.2,17.9,22.9,96.8
1340,1974,ABA,Utah Stars,UTS,True,84,20310,42.9,88.8,0.483,...,0.789,13.8,31.6,45.4,22.4,8.4,4.2,17.1,23.2,105.6
1341,1974,ABA,Virginia Squires,VIR,True,84,20260,38.7,85.6,0.452,...,0.768,15.2,29.6,44.8,18.8,8.0,4.2,19.3,24.5,100.9

In [264]:
df_rookie = pd.read_csv('nba/nba_all_season_rookie_season.csv')
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,dreb_pct,usg_pct,ts_pct,ast_pct,season,pts_rookie_season,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.071,0.169,0.487,0.248,1996-97,3.9,1.5,2.4,0.169,0.487
1,Gaylon Nickerson,WAS,28,190.50,86.182480,Northwestern Oklahoma,USA,1994,2,34,...,0.111,0.174,0.497,0.043,1996-97,NaN,NaN,NaN,NaN,NaN
2,George Lynch,VAN,26,203.20,103.418976,North Carolina,USA,1993,1,12,...,0.185,0.175,0.512,0.125,1996-97,NaN,NaN,NaN,NaN,NaN
3,George McCloud,LAL,30,203.20,102.058200,Florida State,USA,1989,1,7,...,0.111,0.206,0.527,0.125,1996-97,NaN,NaN,NaN,NaN,NaN
4,George Zidek,DEN,23,213.36,119.748288,UCLA,USA,1995,1,22,...,0.169,0.195,0.500,0.064,1996-97,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12839,Joel Embiid,PHI,29,213.36,127.005760,Kansas,Cameroon,2014,1,3,...,0.243,0.370,0.655,0.233,2022-23,NaN,NaN,NaN,NaN,NaN
12840,John Butler Jr.,POR,20,213.36,86.182480,Florida State,USA,Undrafted,Undrafted,Undrafted,...,0.065,0.102,0.411,0.066,2022-23,2.4,0.9,0.6,0.102,0.411
12841,John Collins,ATL,25,205.74,102.511792,Wake Forest,USA,2017,1,19,...,0.180,0.168,0.593,0.052,2022-23,10.5,7.3,1.3,0.174,0.620
12842,Jericho Sims,NYK,24,208.28,113.398000,Texas,USA,2021,2,58,...,0.175,0.074,0.780,0.044,2022-23,2.2,4.1,0.5,0.068,0.674
12843,JaMychal Green,GSW,33,205.74,102.965384,Alabama,USA,Undrafted,Undrafted,Undrafted,...,0.164,0.169,0.650,0.094,2022-23,2.6,1.9,0.2,0.171,0.603

In [265]:
# Fusionner les DataFrames en utilisant une fusion interne sur la colonne 'player_name'
df_rookie = pd.merge(df_rookie, df_career[['player_name','num_seasons' ,'hof']], on='player_name', how='inner')

# Renommer la colonne 'hof' pour 'hall of fame' si nÃ©cessaire
df_rookie = df_rookie.rename(columns={'hof': 'hall_of_fame'})
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,ts_pct,ast_pct,season,pts_rookie_season,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.487,0.248,1996-97,3.9,1.5,2.4,0.169,0.487,11,False
1,Randy Livingston,ATL,23,193.04,95.254320,Louisiana State,USA,1996,2,42,...,0.352,0.104,1997-98,3.9,1.5,2.4,0.169,0.487,11,False
2,Randy Livingston,PHX,24,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.676,0.250,1998-99,3.9,1.5,2.4,0.169,0.487,11,False
3,Randy Livingston,PHX,25,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.476,0.254,1999-00,3.9,1.5,2.4,0.169,0.487,11,False
4,Randy Livingston,GSW,26,193.04,95.254320,Louisiana State,USA,1996,2,42,...,0.000,0.333,2000-01,3.9,1.5,2.4,0.169,0.487,11,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,Trey Murphy III,NOP,23,203.20,93.439952,Virginia,USA,2021,1,17,...,0.650,0.063,2022-23,5.4,2.4,0.6,0.147,0.558,1,False
12049,Terry Taylor,IND,22,195.58,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,0.656,0.081,2021-22,9.6,5.2,1.2,0.151,0.656,1,False
12050,Terry Taylor,CHI,23,193.04,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,0.557,0.052,2022-23,9.6,5.2,1.2,0.151,0.656,1,False
12051,Brandon Boston Jr.,LAC,21,198.12,85.275296,Kentucky,USA,2021,2,51,...,0.515,0.129,2022-23,NaN,NaN,NaN,NaN,NaN,1,False
12052,Johnny Davis,WAS,21,193.04,88.450440,Wisconsin,USA,2022,1,10,...,0.446,0.100,2022-23,5.8,2.3,1.0,0.192,0.446,10,False

In [266]:
df_rookie.loc[df_rookie['player_name'] == 'Rudy Gobert']

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,ts_pct,ast_pct,season,pts_rookie_season,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame
9355,Rudy Gobert,UTA,22,215.9,111.130040,None,France,2013,1,27,...,0.507,0.026,2013-14,2.3,3.4,0.2,0.137,0.507,9,False
9356,Rudy Gobert,UTA,23,215.9,111.130040,None,France,2013,1,27,...,0.627,0.087,2014-15,2.3,3.4,0.2,0.137,0.507,9,False
9357,Rudy Gobert,UTA,24,215.9,111.130040,None,France,2013,1,27,...,0.582,0.073,2015-16,2.3,3.4,0.2,0.137,0.507,9,False
9358,Rudy Gobert,UTA,25,215.9,111.130040,None,France,2013,1,27,...,0.681,0.057,2016-17,2.3,3.4,0.2,0.137,0.507,9,False
9359,Rudy Gobert,UTA,26,215.9,111.130040,None,France,2013,1,27,...,0.657,0.068,2017-18,2.3,3.4,0.2,0.137,0.507,9,False
9360,Rudy Gobert,UTA,27,215.9,111.130040,None,France,2013,1,27,...,0.682,0.095,2018-19,2.3,3.4,0.2,0.137,0.507,9,False
9361,Rudy Gobert,UTA,28,215.9,117.026736,None,France,2013,1,27,...,0.699,0.065,2019-20,2.3,3.4,0.2,0.137,0.507,9,False
9362,Rudy Gobert,UTA,29,215.9,117.026736,None,France,2013,1,27,...,0.683,0.059,2020-21,2.3,3.4,0.2,0.137,0.507,9,False
9363,Rudy Gobert,UTA,30,215.9,117.026736,None,France,2013,1,27,...,0.732,0.052,2021-22,2.3,3.4,0.2,0.137,0.507,9,False
9364,Rudy Gobert,MIN,31,215.9,117.026736,None,France,2013,1,27,...,0.675,0.058,2022-23,2.3,3.4,0.2,0.137,0.507,9,False

In [267]:
# Grouper les donnÃ©es dans df_award par joueur pour vÃ©rifier si au moins une occurrence de "True" existe
player_award_status = df_award.groupby('player_name')['winner'].any().reset_index()

# Fusionner df_rookie avec les rÃ©sultats du groupage
df_rookie = pd.merge(df_rookie, player_award_status, on='player_name', how='left')

# Remplacer les valeurs NaN par False dans la colonne 'winner'
df_rookie['winner'].fillna(False, inplace=True)

# Renommer la colonne 'winner' en 'indiv_award' si nÃ©cessaire
df_rookie = df_rookie.rename(columns={'winner': 'indiv_award'})
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,ast_pct,season,pts_rookie_season,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame,indiv_award
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.248,1996-97,3.9,1.5,2.4,0.169,0.487,11,False,False
1,Randy Livingston,ATL,23,193.04,95.254320,Louisiana State,USA,1996,2,42,...,0.104,1997-98,3.9,1.5,2.4,0.169,0.487,11,False,False
2,Randy Livingston,PHX,24,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.250,1998-99,3.9,1.5,2.4,0.169,0.487,11,False,False
3,Randy Livingston,PHX,25,193.04,94.800728,Louisiana State,USA,1996,2,42,...,0.254,1999-00,3.9,1.5,2.4,0.169,0.487,11,False,False
4,Randy Livingston,GSW,26,193.04,95.254320,Louisiana State,USA,1996,2,42,...,0.333,2000-01,3.9,1.5,2.4,0.169,0.487,11,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,Trey Murphy III,NOP,23,203.20,93.439952,Virginia,USA,2021,1,17,...,0.063,2022-23,5.4,2.4,0.6,0.147,0.558,1,False,False
12049,Terry Taylor,IND,22,195.58,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,0.081,2021-22,9.6,5.2,1.2,0.151,0.656,1,False,False
12050,Terry Taylor,CHI,23,193.04,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,0.052,2022-23,9.6,5.2,1.2,0.151,0.656,1,False,False
12051,Brandon Boston Jr.,LAC,21,198.12,85.275296,Kentucky,USA,2021,2,51,...,0.129,2022-23,NaN,NaN,NaN,NaN,NaN,1,False,False
12052,Johnny Davis,WAS,21,193.04,88.450440,Wisconsin,USA,2022,1,10,...,0.100,2022-23,5.8,2.3,1.0,0.192,0.446,10,False,False

In [268]:
df_rookie.loc[df_rookie['player_name'] == 'Rudy Gobert']

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,ast_pct,season,pts_rookie_season,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame,indiv_award
9355,Rudy Gobert,UTA,22,215.9,111.130040,None,France,2013,1,27,...,0.026,2013-14,2.3,3.4,0.2,0.137,0.507,9,False,True
9356,Rudy Gobert,UTA,23,215.9,111.130040,None,France,2013,1,27,...,0.087,2014-15,2.3,3.4,0.2,0.137,0.507,9,False,True
9357,Rudy Gobert,UTA,24,215.9,111.130040,None,France,2013,1,27,...,0.073,2015-16,2.3,3.4,0.2,0.137,0.507,9,False,True
9358,Rudy Gobert,UTA,25,215.9,111.130040,None,France,2013,1,27,...,0.057,2016-17,2.3,3.4,0.2,0.137,0.507,9,False,True
9359,Rudy Gobert,UTA,26,215.9,111.130040,None,France,2013,1,27,...,0.068,2017-18,2.3,3.4,0.2,0.137,0.507,9,False,True
9360,Rudy Gobert,UTA,27,215.9,111.130040,None,France,2013,1,27,...,0.095,2018-19,2.3,3.4,0.2,0.137,0.507,9,False,True
9361,Rudy Gobert,UTA,28,215.9,117.026736,None,France,2013,1,27,...,0.065,2019-20,2.3,3.4,0.2,0.137,0.507,9,False,True
9362,Rudy Gobert,UTA,29,215.9,117.026736,None,France,2013,1,27,...,0.059,2020-21,2.3,3.4,0.2,0.137,0.507,9,False,True
9363,Rudy Gobert,UTA,30,215.9,117.026736,None,France,2013,1,27,...,0.052,2021-22,2.3,3.4,0.2,0.137,0.507,9,False,True
9364,Rudy Gobert,MIN,31,215.9,117.026736,None,France,2013,1,27,...,0.058,2022-23,2.3,3.4,0.2,0.137,0.507,9,False,True

In [269]:
# Convertir la colonne 'season' de df_rookie en int64 en extrayant les quatre premiers caractÃ¨res
df_rookie['season_year'] = df_rookie['season'].str[:4].astype(int)
df_r_stock = df_rookie['season']
# Fusionner df_rookie avec df_playoff sur la colonne 'team_abbreviation' et 'season_year'
df_rookie = pd.merge(df_rookie, df_playoff[['team_abbreviation', 'season', 'playoffs']], 
                     left_on=['team_abbreviation', 'season_year'], 
                     right_on=['team_abbreviation', 'season'], 
                     how='left')

# Remplacer les valeurs NaN par False dans la colonne 'playoffs'
df_rookie['playoffs'].fillna(False, inplace=True)
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame,indiv_award,season_year,season_y,playoffs
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1996,1996.0,True
1,Randy Livingston,ATL,23,193.04,95.254320,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1997,1997.0,True
2,Randy Livingston,PHX,24,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1998,NaN,False
3,Randy Livingston,PHX,25,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1999,NaN,False
4,Randy Livingston,GSW,26,193.04,95.254320,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,2000,2000.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,Trey Murphy III,NOP,23,203.20,93.439952,Virginia,USA,2021,1,17,...,2.4,0.6,0.147,0.558,1,False,False,2022,2022.0,True
12049,Terry Taylor,IND,22,195.58,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,5.2,1.2,0.151,0.656,1,False,False,2021,2021.0,False
12050,Terry Taylor,CHI,23,193.04,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,5.2,1.2,0.151,0.656,1,False,False,2022,2022.0,True
12051,Brandon Boston Jr.,LAC,21,198.12,85.275296,Kentucky,USA,2021,2,51,...,NaN,NaN,NaN,NaN,1,False,False,2022,2022.0,False
12052,Johnny Davis,WAS,21,193.04,88.450440,Wisconsin,USA,2022,1,10,...,2.3,1.0,0.192,0.446,10,False,False,2022,2022.0,False

In [270]:
df_rookie.loc[df_rookie['player_name'] == 'Giannis Antetokounmpo']

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame,indiv_award,season_year,season_y,playoffs
9265,Giannis Antetokounmpo,MIL,19,205.74,92.986360,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2013,2013.0,True
9266,Giannis Antetokounmpo,MIL,20,210.82,98.429464,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2014,2014.0,False
9267,Giannis Antetokounmpo,MIL,21,210.82,100.697424,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2015,2015.0,True
9268,Giannis Antetokounmpo,MIL,22,210.82,100.697424,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2016,2016.0,False
9269,Giannis Antetokounmpo,MIL,23,210.82,100.697424,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2017,2017.0,True
9270,Giannis Antetokounmpo,MIL,24,210.82,109.769264,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2018,2018.0,True
9271,Giannis Antetokounmpo,MIL,25,210.82,109.769264,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2019,2019.0,True
9272,Giannis Antetokounmpo,MIL,26,210.82,109.769264,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2020,2020.0,True
9273,Giannis Antetokounmpo,MIL,27,210.82,109.769264,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2021,2021.0,True
9274,Giannis Antetokounmpo,MIL,28,213.36,110.222856,None,Greece,2013,1,15,...,4.4,1.9,0.15,0.518,9,False,True,2022,2022.0,True

In [271]:
df_rookie.drop(columns=['season_y'], inplace=True)
df_rookie['season'] = df_r_stock
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,reb_rookie_season,ast_rookie_season,usg_pct_rookie_season,ts_pct_rookie_season,num_seasons,hall_of_fame,indiv_award,season_year,playoffs,season
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1996,True,1996-97
1,Randy Livingston,ATL,23,193.04,95.254320,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1997,True,1997-98
2,Randy Livingston,PHX,24,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1998,False,1998-99
3,Randy Livingston,PHX,25,193.04,94.800728,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,1999,False,1999-00
4,Randy Livingston,GSW,26,193.04,95.254320,Louisiana State,USA,1996,2,42,...,1.5,2.4,0.169,0.487,11,False,False,2000,False,2000-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,Trey Murphy III,NOP,23,203.20,93.439952,Virginia,USA,2021,1,17,...,2.4,0.6,0.147,0.558,1,False,False,2022,True,2022-23
12049,Terry Taylor,IND,22,195.58,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,5.2,1.2,0.151,0.656,1,False,False,2021,False,2021-22
12050,Terry Taylor,CHI,23,193.04,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,5.2,1.2,0.151,0.656,1,False,False,2022,True,2022-23
12051,Brandon Boston Jr.,LAC,21,198.12,85.275296,Kentucky,USA,2021,2,51,...,NaN,NaN,NaN,NaN,1,False,False,2022,False,2022-23
12052,Johnny Davis,WAS,21,193.04,88.450440,Wisconsin,USA,2022,1,10,...,2.3,1.0,0.192,0.446,10,False,False,2022,False,2022-23

In [272]:
data = {
    'nba_champion': ['CHI','CHI','CHI','SAS','LAL','LAL','LAL','SAS','DET','SAS','MIA','SAS','BOS','LAL','LAL','DAL','MIA','MIA','SAS','GSW','CLE','GSW','GSW',
                     'TOR','LAL','MIL','GSW'],
    'mvp_finals': ['Michael Jordan','Michael Jordan','Michael Jordan','Tim Duncan',"Shaquille O'Neal","Shaquille O'Neal","Shaquille O'Neal",'Tim Duncan',
                   'Chauncey Billups','Tim Duncan','Dwayne Wade','Tony Parker','Paul Pierce','Kobe Bryant','Kobe Bryant','Dirk Nowitzki','LeBron James',
                   'LeBron James','Kawhi Leonard','Andre Iguodala','LeBron James','Kevin Durant','Kevin Durant','Kawhi Leonard','LeBron James',
                   'Giannis Antetokounmpo','Stephen Curry'],
    'year': [1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022],
    'finalist': ['SEA','UTA','UTA','NYK','IND','PHI','NJN','NJN','LAL','DET','DAL','CLE','LAL','ORL','BOS','MIA','OKC','SAS','MIA','CLE','GSW','CLE','CLE',
                 'GSW','MIA','PHX','BOS']
}

# CrÃ©ation de la DataFrame
df = pd.DataFrame(data)
df

   nba_champion             mvp_finals  year finalist
0           CHI         Michael Jordan  1996      SEA
1           CHI         Michael Jordan  1997      UTA
2           CHI         Michael Jordan  1998      UTA
3           SAS             Tim Duncan  1999      NYK
4           LAL       Shaquille O'Neal  2000      IND
5           LAL       Shaquille O'Neal  2001      PHI
6           LAL       Shaquille O'Neal  2002      NJN
7           SAS             Tim Duncan  2003      NJN
8           DET       Chauncey Billups  2004      LAL
9           SAS             Tim Duncan  2005      DET
10          MIA            Dwayne Wade  2006      DAL
11          SAS            Tony Parker  2007      CLE
12          BOS            Paul Pierce  2008      LAL
13          LAL            Kobe Bryant  2009      ORL
14          LAL            Kobe Bryant  2010      BOS
15          DAL          Dirk Nowitzki  2011      MIA
16          MIA           LeBron James  2012      OKC
17          MIA           LeBron James  2013      SAS
18          SAS          Kawhi Leonard  2014      MIA
19          GSW         Andre Iguodala  2015      CLE
20          CLE           LeBron James  2016      GSW
21          GSW           Kevin Durant  2017      CLE
22          GSW           Kevin Durant  2018      CLE
23          TOR          Kawhi Leonard  2019      GSW
24          LAL           LeBron James  2020      MIA
25          MIL  Giannis Antetokounmpo  2021      PHX
26          GSW          Stephen Curry  2022      BOS

In [273]:
# Fusionner df_rookie avec df en fonction de l'annÃ©e correspondante
df_rookie = pd.merge(df_rookie, df, left_on='season_year', right_on='year', how='left')
df_rookie

,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,draft_number,...,num_seasons,hall_of_fame,indiv_award,season_year,playoffs,season,nba_champion,mvp_finals,year,finalist
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1996,2,42,...,11,False,False,1996,True,1996-97,CHI,Michael Jordan,1996,SEA
1,Randy Livingston,ATL,23,193.04,95.254320,Louisiana State,USA,1996,2,42,...,11,False,False,1997,True,1997-98,CHI,Michael Jordan,1997,UTA
2,Randy Livingston,PHX,24,193.04,94.800728,Louisiana State,USA,1996,2,42,...,11,False,False,1998,False,1998-99,CHI,Michael Jordan,1998,UTA
3,Randy Livingston,PHX,25,193.04,94.800728,Louisiana State,USA,1996,2,42,...,11,False,False,1999,False,1999-00,SAS,Tim Duncan,1999,NYK
4,Randy Livingston,GSW,26,193.04,95.254320,Louisiana State,USA,1996,2,42,...,11,False,False,2000,False,2000-01,LAL,Shaquille O'Neal,2000,IND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12048,Trey Murphy III,NOP,23,203.20,93.439952,Virginia,USA,2021,1,17,...,1,False,False,2022,True,2022-23,GSW,Stephen Curry,2022,BOS
12049,Terry Taylor,IND,22,195.58,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,1,False,False,2021,False,2021-22,MIL,Giannis Antetokounmpo,2021,PHX
12050,Terry Taylor,CHI,23,193.04,104.326160,Austin Peay,USA,Undrafted,Undrafted,Undrafted,...,1,False,False,2022,True,2022-23,GSW,Stephen Curry,2022,BOS
12051,Brandon Boston Jr.,LAC,21,198.12,85.275296,Kentucky,USA,2021,2,51,...,1,False,False,2022,False,2022-23,GSW,Stephen Curry,2022,BOS
12052,Johnny Davis,WAS,21,193.04,88.450440,Wisconsin,USA,2022,1,10,...,10,False,False,2022,False,2022-23,GSW,Stephen Curry,2022,BOS

In [274]:
df_rookie.to_csv('data_hof_award.csv', index=False)